In [1]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder,StandardScaler,LabelEncoder # Handling categorical data
from sklearn.impute import SimpleImputer # handling missing values
from sklearn.pipeline import Pipeline # Pipelines
from sklearn.compose import ColumnTransformer
# Model 
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score, roc_curve, auc
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier,AdaBoostClassifier,ExtraTreesClassifier,GradientBoostingClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC



In [2]:
## Data Ingestion
prog = pd.read_csv("data/Training.csv")

In [3]:
## Independent and Dependent column

X  = prog.drop(labels=['prognosis'], axis=1)
Y  = prog['prognosis']

In [4]:
# Define which column should be ordinal encoded and which should be one hot encoded
# No numerical Column is in the data sets
categorical_columns = X.select_dtypes(include="object").columns

In [5]:
# Categorical pipeline

cat_pipeline = Pipeline(
      steps=[
          ('imputer',SimpleImputer(strategy='most_frequent')),
          ("OneHotEncoder",OneHotEncoder(sparse=False,drop='first')),
          ('scalar',StandardScaler())
      ]

)

proccessor = ColumnTransformer([
    ('cat_pipeline', cat_pipeline, categorical_columns)
])

In [6]:
## Train test split the data sets
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, Y, test_size=0.30, random_state=30)

In [7]:
X_train = pd.DataFrame(proccessor.fit_transform(X_train), columns=proccessor.get_feature_names_out())
X_test = pd.DataFrame(proccessor.transform(X_test), columns= proccessor.get_feature_names_out())

e:\ML projects\MedicineRecommendationSystem\venv\lib\site-packages\sklearn\preprocessing\_encoders.py:975: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


In [8]:
## Ordinal encoding fot dependent variable
label_encoder  = LabelEncoder()
y_train_ord = label_encoder.fit_transform(y_train)
y_test_ord = label_encoder.transform(y_test)

In [9]:
## Evaluating the Model
def evaluate_classification_model(true, predicted, prob_predictions=None):
    # Accuracy
    accuracy = accuracy_score(true, predicted)
    
    # Precision
    precision = precision_score(true, predicted,average='macro')
    
    # Recall
    recall = recall_score(true, predicted,average='macro')
    
    # F1-Score
    f1 = f1_score(true, predicted,average='macro')
    
    # Confusion Matrix
    cm = confusion_matrix(true, predicted)
    
    return accuracy, precision, recall, f1,cm

In [10]:
## Train multiple models
## Model Evaluation

models = {
    "LogisticRegression":LogisticRegression(),
    "DecisionTreeClassifier":DecisionTreeClassifier(),
    "RandomForestClassifier":RandomForestClassifier(),
    "Extratressclassifier":ExtraTreesClassifier(),
    "KNeighborsClassifier":KNeighborsClassifier(n_neighbors=5),
    "AdaBoostClassifier":AdaBoostClassifier(),
    "GradientBoostingClassifier":GradientBoostingClassifier(),
    "SVC":SVC()
}


train_model_list = []
model_list = []
accuracy_list = []

for i in range(len(list(models))):
    model = list(models.values())[i]
    model.fit(X_train,y_train_ord)

    # Make Prediction

    y_pred = model.predict(X_test)

    accuracy, precision, recall, f1,cm =  evaluate_classification_model(y_test_ord,y_pred)


    print(list(models.keys())[i])
    model_list.append(list(models.keys())[i])

    print("Model Training Performance")
    print("Accuracy", accuracy)
    print("Precision", precision)
    print("Recall score", recall)
    print("f1_score", f1)
    print("Confusion Matrix", cm)


    accuracy_list.append(accuracy)

    print("="*35)

    print("\n")

LogisticRegression
Model Training Performance
Accuracy 1.0
Precision 1.0
Recall score 1.0
f1_score 1.0
Confusion Matrix [[34  0  0 ...  0  0  0]
 [ 0 31  0 ...  0  0  0]
 [ 0  0 26 ...  0  0  0]
 ...
 [ 0  0  0 ... 39  0  0]
 [ 0  0  0 ...  0 38  0]
 [ 0  0  0 ...  0  0 40]]


DecisionTreeClassifier
Model Training Performance
Accuracy 1.0
Precision 1.0
Recall score 1.0
f1_score 1.0
Confusion Matrix [[34  0  0 ...  0  0  0]
 [ 0 31  0 ...  0  0  0]
 [ 0  0 26 ...  0  0  0]
 ...
 [ 0  0  0 ... 39  0  0]
 [ 0  0  0 ...  0 38  0]
 [ 0  0  0 ...  0  0 40]]


RandomForestClassifier
Model Training Performance
Accuracy 1.0
Precision 1.0
Recall score 1.0
f1_score 1.0
Confusion Matrix [[34  0  0 ...  0  0  0]
 [ 0 31  0 ...  0  0  0]
 [ 0  0 26 ...  0  0  0]
 ...
 [ 0  0  0 ... 39  0  0]
 [ 0  0  0 ...  0 38  0]
 [ 0  0  0 ...  0  0 40]]


Extratressclassifier
Model Training Performance
Accuracy 1.0
Precision 1.0
Recall score 1.0
f1_score 1.0
Confusion Matrix [[34  0  0 ...  0  0  0]
 [ 0 31  0 

e:\ML projects\MedicineRecommendationSystem\venv\lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


AdaBoostClassifier
Model Training Performance
Accuracy 0.13279132791327913
Precision 0.12241846556396598
Recall score 0.14634146341463414
f1_score 0.12286814597469282
Confusion Matrix [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


GradientBoostingClassifier
Model Training Performance
Accuracy 1.0
Precision 1.0
Recall score 1.0
f1_score 1.0
Confusion Matrix [[34  0  0 ...  0  0  0]
 [ 0 31  0 ...  0  0  0]
 [ 0  0 26 ...  0  0  0]
 ...
 [ 0  0  0 ... 39  0  0]
 [ 0  0  0 ...  0 38  0]
 [ 0  0  0 ...  0  0 40]]


SVC
Model Training Performance
Accuracy 1.0
Precision 1.0
Recall score 1.0
f1_score 1.0
Confusion Matrix [[34  0  0 ...  0  0  0]
 [ 0 31  0 ...  0  0  0]
 [ 0  0 26 ...  0  0  0]
 ...
 [ 0  0  0 ... 39  0  0]
 [ 0  0  0 ...  0 38  0]
 [ 0  0  0 ...  0  0 40]]




In [18]:
import pickle

# load databasedataset===================================

sym_des = pd.read_csv(r"E:\ML projects\MedicineRecommendationSystem\notebooks\data\symtoms_df.csv")
precautions = pd.read_csv(r"E:\ML projects\MedicineRecommendationSystem\notebooks\data\precautions_df.csv")
workout = pd.read_csv(r"E:\ML projects\MedicineRecommendationSystem\notebooks\data\workout_df.csv")
description = pd.read_csv(r"E:\ML projects\MedicineRecommendationSystem\notebooks\data\description.csv")
medications = pd.read_csv(r'E:\ML projects\MedicineRecommendationSystem\notebooks\data\medications.csv')
diets = pd.read_csv(r"E:\ML projects\MedicineRecommendationSystem\notebooks\data\diets.csv")


# load model===========================================
svc = pickle.load(open(r'E:\ML projects\MedicineRecommendationSystem\artifacts\model.pkl','rb'))
preprocessor = pickle.load(open(r'E:\ML projects\MedicineRecommendationSystem\artifacts\preprocessor.pkl','rb'))
# load label encoder===========================================
label_encoder = pickle.load(open(r'E:\ML projects\MedicineRecommendationSystem\artifacts\label_encoder.pkl','rb'))


#============================================================
# custome and helping functions
#==========================helper funtions================
def helper(dis):
    desc = description[description['Disease'] == dis]['Description']
    desc = " ".join([w for w in desc])

    pre = precautions[precautions['Disease'] == dis][['Precaution_1', 'Precaution_2', 'Precaution_3', 'Precaution_4']]
    pre = [col for col in pre.values]

    med = medications[medications['Disease'] == dis]['Medication']
    med = [med for med in med.values]

    die = diets[diets['Disease'] == dis]['Diet']
    die = [die for die in die.values]

    wrkout = workout[workout['disease'] == dis] ['workout']


    return desc,pre,med,die,wrkout

symptoms_dict = {'itching': 0, 'skin_rash': 1, 'nodal_skin_eruptions': 2, 'continuous_sneezing': 3, 'shivering': 4, 'chills': 5, 'joint_pain': 6, 'stomach_pain': 7, 'acidity': 8, 'ulcers_on_tongue': 9, 'muscle_wasting': 10, 'vomiting': 11, 'burning_micturition': 12, 'spotting_ urination': 13, 'fatigue': 14, 'weight_gain': 15, 'anxiety': 16, 'cold_hands_and_feets': 17, 'mood_swings': 18, 'weight_loss': 19, 'restlessness': 20, 'lethargy': 21, 'patches_in_throat': 22, 'irregular_sugar_level': 23, 'cough': 24, 'high_fever': 25, 'sunken_eyes': 26, 'breathlessness': 27, 'sweating': 28, 'dehydration': 29, 'indigestion': 30, 'headache': 31, 'yellowish_skin': 32, 'dark_urine': 33, 'nausea': 34, 'loss_of_appetite': 35, 'pain_behind_the_eyes': 36, 'back_pain': 37, 'constipation': 38, 'abdominal_pain': 39, 'diarrhoea': 40, 'mild_fever': 41, 'yellow_urine': 42, 'yellowing_of_eyes': 43, 'acute_liver_failure': 44, 'fluid_overload': 45, 'swelling_of_stomach': 46, 'swelled_lymph_nodes': 47, 'malaise': 48, 'blurred_and_distorted_vision': 49, 'phlegm': 50, 'throat_irritation': 51, 'redness_of_eyes': 52, 'sinus_pressure': 53, 'runny_nose': 54, 'congestion': 55, 'chest_pain': 56, 'weakness_in_limbs': 57, 'fast_heart_rate': 58, 'pain_during_bowel_movements': 59, 'pain_in_anal_region': 60, 'bloody_stool': 61, 'irritation_in_anus': 62, 'neck_pain': 63, 'dizziness': 64, 'cramps': 65, 'bruising': 66, 'obesity': 67, 'swollen_legs': 68, 'swollen_blood_vessels': 69, 'puffy_face_and_eyes': 70, 'enlarged_thyroid': 71, 'brittle_nails': 72, 'swollen_extremeties': 73, 'excessive_hunger': 74, 'extra_marital_contacts': 75, 'drying_and_tingling_lips': 76, 'slurred_speech': 77, 'knee_pain': 78, 'hip_joint_pain': 79, 'muscle_weakness': 80, 'stiff_neck': 81, 'swelling_joints': 82, 'movement_stiffness': 83, 'spinning_movements': 84, 'loss_of_balance': 85, 'unsteadiness': 86, 'weakness_of_one_body_side': 87, 'loss_of_smell': 88, 'bladder_discomfort': 89, 'foul_smell_of urine': 90, 'continuous_feel_of_urine': 91, 'passage_of_gases': 92, 'internal_itching': 93, 'toxic_look_(typhos)': 94, 'depression': 95, 'irritability': 96, 'muscle_pain': 97, 'altered_sensorium': 98, 'red_spots_over_body': 99, 'belly_pain': 100, 'abnormal_menstruation': 101, 'dischromic _patches': 102, 'watering_from_eyes': 103, 'increased_appetite': 104, 'polyuria': 105, 'family_history': 106, 'mucoid_sputum': 107, 'rusty_sputum': 108, 'lack_of_concentration': 109, 'visual_disturbances': 110, 'receiving_blood_transfusion': 111, 'receiving_unsterile_injections': 112, 'coma': 113, 'stomach_bleeding': 114, 'distention_of_abdomen': 115, 'history_of_alcohol_consumption': 116, 'fluid_overload.1': 117, 'blood_in_sputum': 118, 'prominent_veins_on_calf': 119, 'palpitations': 120, 'painful_walking': 121, 'pus_filled_pimples': 122, 'blackheads': 123, 'scurring': 124, 'skin_peeling': 125, 'silver_like_dusting': 126, 'small_dents_in_nails': 127, 'inflammatory_nails': 128, 'blister': 129, 'red_sore_around_nose': 130, 'yellow_crust_ooze': 131}
diseases_list = {15: 'Fungal infection', 4: 'Allergy', 16: 'GERD', 9: 'Chronic cholestasis', 14: 'Drug Reaction', 33: 'Peptic ulcer diseae', 1: 'AIDS', 12: 'Diabetes ', 17: 'Gastroenteritis', 6: 'Bronchial Asthma', 23: 'Hypertension ', 30: 'Migraine', 7: 'Cervical spondylosis', 32: 'Paralysis (brain hemorrhage)', 28: 'Jaundice', 29: 'Malaria', 8: 'Chicken pox', 11: 'Dengue', 37: 'Typhoid', 40: 'hepatitis A', 19: 'Hepatitis B', 20: 'Hepatitis C', 21: 'Hepatitis D', 22: 'Hepatitis E', 3: 'Alcoholic hepatitis', 36: 'Tuberculosis', 10: 'Common Cold', 34: 'Pneumonia', 13: 'Dimorphic hemmorhoids(piles)', 18: 'Heart attack', 39: 'Varicose veins', 26: 'Hypothyroidism', 24: 'Hyperthyroidism', 25: 'Hypoglycemia', 31: 'Osteoarthristis', 5: 'Arthritis', 0: '(vertigo) Paroymsal  Positional Vertigo', 2: 'Acne', 38: 'Urinary tract infection', 35: 'Psoriasis', 27: 'Impetigo'}

def get_predicted_value(patient_symptoms):
    """
    patient_symptoms: list of symptoms
    """
    input_data = ["No"] * len(symptoms_dict)
    for symptom in patient_symptoms:
        if symptom in symptoms_dict:
            input_data[symptoms_dict[symptom]] = "Yes"
        else:
            print(f"Symptom '{symptom}' not found in the symptoms dictionary.")
            return None
    input_data = pd.DataFrame([input_data], columns=symptoms_dict.keys())
    input_data = pd.DataFrame(preprocessor.transform(input_data), columns=preprocessor.get_feature_names_out())
    prediction = svc.predict(input_data)
    # FIX: Convert prediction to integer type
    prediction = prediction.astype(int)
    predicted_disease = label_encoder.inverse_transform(prediction)
    desc, pre, med, die, wrkout = helper(predicted_disease[0])
    return predicted_disease[0], desc, pre, med, die, wrkout
# test the model
import numpy as np
if __name__ == "__main__":
    # Example usage
    patient_symptoms = ['itching', 'skin_rash', 'nodal_skin_eruptions']
    predicted_disease, desc, pre, med, die, wrkout = get_predicted_value(patient_symptoms)
    print(f"Predicted disease: {predicted_disease}")
    print(f"Description: {desc}")
    print(f"Precautions: {pre}")
    print(f"Medications: {med}")
    print(f"Diet: {die}")
    print(f"Workout: {wrkout}")
#=============================================================
#=============================================================
#=============================================================
#=============================================================

Predicted disease: Fungal infection
Description: Fungal infection is a common skin condition caused by fungi.
Precautions: [array(['bath twice', 'use detol or neem in bathing water',
       'keep infected area dry', 'use clean cloths'], dtype=object)]
Medications: ["['Antifungal Cream', 'Fluconazole', 'Terbinafine', 'Clotrimazole', 'Ketoconazole']"]
Diet: ["['Antifungal Diet', 'Probiotics', 'Garlic', 'Coconut oil', 'Turmeric']"]
Workout: 0           Avoid sugary foods
1           Consume probiotics
2    Increase intake of garlic
3       Include yogurt in diet
4        Limit processed foods
5                Stay hydrated
6            Consume green tea
7       Eat foods rich in zinc
8     Include turmeric in diet
9    Eat fruits and vegetables
Name: workout, dtype: object


e:\ML projects\MedicineRecommendationSystem\venv\lib\site-packages\sklearn\base.py:458: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  warnings.warn(
